server:
  port: 8090



logging:
  level:
    org.springframework.security: DEBUG
    log4j.logger.org.hibernate.SQL: DEBUG
    com.techolution: DEBUG
    
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://10.128.0.12:3306/mauritius_smartwater?&useSSL=false
    username: admin
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 5
    hikari:
      maximum-pool-size: 5
  application:
    name: notificationservice
  data:
    redis:
      repositories:
        enabled: true
  redis:
    host: 10.128.0.12
    port: 32768
    timeout:
      seconds: 3600

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1